[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"
base = "light"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 25
